# -*- coding: utf-8 -*-
"""voice_interface_multilang.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGb-BEQalcVFB9cAqNhnhiUD_3O9suvj
"""

!pip install gTTS playsound

from google.colab import files
uploaded = files.upload()  # Upload all 4 JSON files together

def get_voice_input():
    return input("🗣 Type your voice query (simulate voice input): ")

from gtts import gTTS
import os
import IPython.display as ipd

def speak_text(text, lang='hi'):
    tts = gTTS(text=text, lang=lang)
    tts.save("response.mp3")
    return ipd.Audio("response.mp3")

import json

datasets = {}

def load_datasets():
    files = {
        'hi': 'legal_qa_dataset_hi.json',
        'bn': 'legal_qa_dataset_bn.json',
        'mr': 'legal_qa_dataset_mr.json',
        'ta': 'legal_qa_dataset_ta.json'
    }

    for lang, file_name in files.items():
        with open(file_name, 'r', encoding='utf-8') as f:
            datasets[lang] = json.load(f)

load_datasets()

def find_answer(query, lang_code):
    for pair in datasets[lang_code]:
        if pair['question'] in query:
            return pair['answer']
    return {
        'hi': "माफ कीजिए, मुझे इसका उत्तर नहीं मिला।",
        'bn': "দুঃখিত, আমি এর উত্তর খুঁজে পাইনি।",
        'mr': "माफ करा, मला याचे उत्तर सापडले नाही.",
        'ta': "மன்னிக்கவும், இதற்கான பதிலை நான் கண்டுபிடிக்க முடியவில்லை."
    }.get(lang_code, "Sorry, answer not found.")

def run_voice_interface():
    lang_map = {
        '1': ('hi', 'हिंदी'),
        '2': ('bn', 'বাংলা'),
        '3': ('mr', 'मराठी'),
        '4': ('ta', 'தமிழ்')
    }

    print("🔤 Select Language:")
    print("1 - Hindi\n2 - Bengali\n3 - Marathi\n4 - Tamil")
    choice = input("Enter 1/2/3/4: ").strip()

    if choice not in lang_map:
        print("❌ Invalid choice.")
        return

    lang_code, lang_name = lang_map[choice]
    print(f"✅ You selected: {lang_name}")

    while True:
        query = get_voice_input()
        if query.lower() in ['exit', 'quit', 'बंद', 'থামো', 'बंद करा', 'நிறுத்து']:
            print("🔚 Exiting...")
            break

        answer = find_answer(query, lang_code)
        print("🤖 Answer:", answer)
        audio = speak_text(answer, lang=lang_code)
        display(audio)

run_voice_interface()